import fs from 'fs/promises';
import path from 'path';
import type { OptimizationSettings } from '../shared/settingsSchema.js';

/**
 * Generate a Cloudflare Pages _headers file with optimal caching rules.
 * This file is placed in the output directory root before deployment.
 */
export async function generateHeaders(outputDir: string, settings?: OptimizationSettings): Promise<void> {
  const cache = settings?.cache.durations;
  const security = settings?.cache.securityHeaders;

  // Build security headers
  const securityLines: string[] = [];
  if (security?.xContentTypeOptions !== false) {
    securityLines.push('  X-Content-Type-Options: nosniff');
  }
  if (security?.xFrameOptions && security.xFrameOptions !== 'disabled') {
    securityLines.push(`  X-Frame-Options: ${security.xFrameOptions}`);
  } else if (!security) {
    securityLines.push('  X-Frame-Options: SAMEORIGIN');
  }
  if (security?.referrerPolicy) {
    securityLines.push(`  Referrer-Policy: ${security.referrerPolicy}`);
  } else if (!security) {
    securityLines.push('  Referrer-Policy: strict-origin-when-cross-origin');
  }
  if (security?.permissionsPolicy !== false) {
    securityLines.push('  Permissions-Policy: camera=(), microphone=(), geolocation=()');
  }
  if (security?.strictTransportSecurity !== false) {
    securityLines.push('  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload');
  }
  if (security?.xXssProtection !== false) {
    securityLines.push('  X-XSS-Protection: 0');
  }
  if (security?.contentSecurityPolicy) {
    securityLines.push(`  Content-Security-Policy: ${security.contentSecurityPolicy}`);
  }

  const htmlCache = cache?.html ?? 'public, max-age=0, must-revalidate';
  const assetCache = cache?.cssJs ?? 'public, max-age=31536000, immutable';
  const fontCache = cache?.fonts ?? 'public, max-age=31536000, immutable';
  const imageHashedCache = cache?.imagesHashed ?? 'public, max-age=31536000, immutable';

  const headersContent = `# Cloudflare Pages headers - Generated by MetricsLab Speed Server

# Security headers for all pages
/*
${securityLines.join('\n')}

# HTML pages: cache briefly, revalidate
/*.html
  Cache-Control: ${htmlCache}

# Root index
/
  Cache-Control: ${htmlCache}

# Static assets with content-hashed filenames: cache forever
/assets/*
  Cache-Control: ${assetCache}

# Fonts: cache forever (content-addressed)
/assets/fonts/*
  Cache-Control: ${fontCache}
  Access-Control-Allow-Origin: *

# Images: cache aggressively
/assets/*.webp
  Cache-Control: ${imageHashedCache}

/assets/*.avif
  Cache-Control: ${imageHashedCache}

/assets/*.jpg
  Cache-Control: ${imageHashedCache}

/assets/*.png
  Cache-Control: ${imageHashedCache}

/assets/*.svg
  Cache-Control: ${imageHashedCache}
`;

  const headersPath = path.join(outputDir, '_headers');
  await fs.writeFile(headersPath, headersContent, 'utf-8');
  console.log(`[headers] Generated _headers file at ${headersPath}`);
}
