import fs from 'fs/promises';
import path from 'path';

/**
 * Generate a Cloudflare Pages _headers file with optimal caching rules.
 * This file is placed in the output directory root before deployment.
 */
export async function generateHeaders(outputDir: string): Promise<void> {
  const headersContent = `# Cloudflare Pages headers - Generated by MetricsLab Speed Server

# Security headers for all pages
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

# HTML pages: cache briefly, revalidate
/*.html
  Cache-Control: public, max-age=3600, stale-while-revalidate=86400

# Root index
/
  Cache-Control: public, max-age=3600, stale-while-revalidate=86400

# Static assets with content-hashed filenames: cache forever
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# Fonts: cache forever (content-addressed)
/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
  Access-Control-Allow-Origin: *

# Images: cache aggressively
/assets/*.webp
  Cache-Control: public, max-age=31536000, immutable

/assets/*.avif
  Cache-Control: public, max-age=31536000, immutable

/assets/*.jpg
  Cache-Control: public, max-age=31536000, immutable

/assets/*.png
  Cache-Control: public, max-age=31536000, immutable

/assets/*.svg
  Cache-Control: public, max-age=31536000, immutable
`;

  const headersPath = path.join(outputDir, '_headers');
  await fs.writeFile(headersPath, headersContent, 'utf-8');
  console.log(`[headers] Generated _headers file at ${headersPath}`);
}
