/**
 * ZarazPlaceholderInjector — If third-party scripts were removed for Zaraz,
 * injects a placeholder comment in the HTML and generates a setup guide file.
 */

import type { CheerioAPI } from 'cheerio';
import type { ThirdPartyReport, DetectedTool } from './ThirdPartyDetector.js';

export interface ZarazInjectionResult {
  injected: boolean;
  setupGuideContent: string | null;
  toolCount: number;
}

/**
 * Inject Zaraz placeholder comment into HTML <head>.
 */
export function injectZarazPlaceholder(
  $: CheerioAPI,
  report: ThirdPartyReport
): ZarazInjectionResult {
  const zarazTools = report.detectedTools.filter(t => t.zarazSupported);

  if (zarazTools.length === 0) {
    return { injected: false, setupGuideContent: null, toolCount: 0 };
  }

  const toolNames = zarazTools.map(t => t.name).join(', ');

  const comment = `\n<!-- \n  ZARAZ SETUP REQUIRED\n  Tools detected and removed: ${toolNames}\n  Add your Cloudflare Zaraz script tag here after configuring Zaraz.\n  See zaraz-setup-guide.md in this deployment for instructions.\n-->\n<!-- ZARAZ_PLACEHOLDER — replace with Zaraz script tag after setup -->\n`;

  const head = $('head').first();
  if (head.length) {
    head.append(comment);
  }

  const setupGuide = generateSetupGuide(report);

  return {
    injected: true,
    setupGuideContent: setupGuide,
    toolCount: zarazTools.length,
  };
}

function generateSetupGuide(report: ThirdPartyReport): string {
  const lines: string[] = [
    '# Cloudflare Zaraz Setup Guide',
    '',
    'The following third-party tracking and marketing tools were detected on your',
    'site and their script tags have been removed for performance optimization.',
    '',
    `Total payload saved: ~${report.estimatedPayloadSavedKb}KB`,
    '',
    '---',
    '',
  ];

  const zarazTools = report.detectedTools.filter(t => t.zarazSupported);
  const nonZarazTools = report.detectedTools.filter(t => !t.zarazSupported);

  if (zarazTools.length > 0) {
    lines.push('## Tools to Configure in Zaraz');
    lines.push('');
    lines.push('These tools are supported by Cloudflare Zaraz and can be restored');
    lines.push('without adding any JavaScript to your site.');
    lines.push('');

    for (const tool of zarazTools) {
      lines.push(`### ${tool.name}`);
      lines.push('');
      if (tool.trackingId) {
        lines.push(`**Tracking ID:** \`${tool.trackingId}\``);
        lines.push('');
      }
      lines.push(`**Estimated payload removed:** ~${tool.payloadKb}KB`);
      lines.push('');
      lines.push('**Setup steps:**');
      lines.push('1. Go to Cloudflare Dashboard > Zaraz > Tools > Add Tool');
      lines.push(`2. Select "${tool.zarazToolName}"`);
      if (tool.trackingId) {
        lines.push(`3. Enter your ${getIdLabel(tool)}: \`${tool.trackingId}\``);
      } else {
        lines.push(`3. Configure with your account credentials`);
      }
      lines.push('4. Save and publish');
      lines.push('');
      lines.push(`**Docs:** https://developers.cloudflare.com/zaraz/get-started/`);
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  if (nonZarazTools.length > 0) {
    lines.push('## Tools Kept with Optimization');
    lines.push('');
    lines.push('These tools are not directly supported by Zaraz. Their scripts');
    lines.push('have been self-hosted on your Cloudflare Pages deployment with');
    lines.push('`defer` loading to reduce performance impact.');
    lines.push('');

    for (const tool of nonZarazTools) {
      lines.push(`- **${tool.name}** (${tool.category}) — ~${tool.payloadKb}KB, self-hosted with defer`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Metrics Lab WP-to-CF Optimizer*');

  return lines.join('\n');
}

function getIdLabel(tool: DetectedTool): string {
  switch (tool.name) {
    case 'Google Analytics 4': return 'Measurement ID';
    case 'Facebook Pixel': return 'Pixel ID';
    case 'Google Ads': return 'Conversion ID';
    case 'HubSpot': return 'Portal ID';
    case 'LinkedIn Insight Tag': return 'Partner ID';
    case 'Hotjar': return 'Site ID';
    case 'Bing Ads': return 'Tag ID';
    case 'Segment': return 'Write Key';
    case 'Twitter/X Ads': return 'Pixel ID';
    default: return 'ID';
  }
}
